### ISSUE TITLE
what license?

### ISSUE THREAD

**Issue by tesch1** [kuitang/mexcpp#2]
hi, this library looks great and I would like to use it, but it's not clear what license you're sharing it under...?  thanks for sharing!

**Comment by kuitang** [comment]
Hi Michael,

Good point. I've added the MIT license.

If it's not too much trouble, I would really appreciate hearing what
platform and version you are building on so I have some idea about
compatibility beyond my own systems.

On Sun, Jan 11, 2015 at 6:21 AM, michael tesch notifications@github.com
wrote:

> hi, this library looks great and I would like to use it, but it's not
> clear what license you're sharing it under...? thanks for sharing!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kuitang/mexcpp/issues/2.

## 

Sincerely,
Kui Tang

**Comment by tesch1** [comment]
Thanks!

I haven't actually tried it yet, didn't want to put the effort in without knowing the license.  mac&linux w/ Eigen - I'll submit pull requests if I need to change anything to get it to work...
